version: '3.8'

services:
  nats:
    image: nats:latest
    command: -js
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data

  debezium:
    image: quay.io/debezium/server:3.0
    depends_on:
      - nats
    volumes:
      - ./debezium/application.properties:/debezium/config/application.properties
      - c:\laragon\www\nats-cli-deployment\univ-reg.creds:/debezium/config/univ-reg.creds
      - debezium-data:/debezium/data
    environment:
      - DEBEZIUM_OPTS=-Xmx256m
    extra_hosts:
      - "host.docker.internal:host-gateway"

  faststream:
    build:
      context: ./consumer
    depends_on:
      - nats
    ports:
      - "8000:8000"
    environment:
      - LOCAL_NATS_URL=nats://nats:4222
      - NATS_CREDS=/app/univ-reg.creds
      - MYSQL_URL=mysql+pymysql://root:@host.docker.internal/registrar-cvsu
    volumes:
      - ./consumer:/app
      - c:\laragon\www\nats-cli-deployment\univ-reg.creds:/app/univ-reg.creds
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  nats-data:
  debezium-data:
