# Debezium Server Configuration

# NATS JetStream Sink Configuration
debezium.sink.type=nats-jetstream
debezium.sink.nats-jetstream.url=nats://192.168.10.130:4222
debezium.sink.nats-jetstream.credentials-file=/debezium/config/univ-reg.creds
debezium.sink.nats-jetstream.create-stream=false
debezium.sink.nats-jetstream.stream.name=EnrollmentData

# Debezium Source Database Configuration (New registrar-cvsu DB)
debezium.source.connector.class=io.debezium.connector.mysql.MySqlConnector
debezium.source.database.hostname=host.docker.internal
debezium.source.database.port=3306
debezium.source.database.user=root
debezium.source.database.password=
debezium.source.database.server.id=184055
debezium.source.database.server.name=academics.enrollment.main

# Point it to your Laravel database and the specific tables you want to stream
debezium.source.database.include.list=registrar-cvsu
debezium.source.table.include.list=registrar-cvsu.student_profile,registrar-cvsu.student_info
debezium.source.topic.prefix=academics.enrollment.main

# Schema and Offset management
debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=/debezium/data/schema_history.dat
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
